
spring:
  application:
    name: QingTingServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.30.87:3306/test
    username: cx
    password: 111111
  data:
    redis:
      host: suansun.top
      port: 6379
      password: 111111
      database: 0
      # 连接超时时间
      timeout: 1800000
      lettuce:
        pool:
          # 最大阻塞等待时间，负数表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 5
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
          max-active: 20
mybatis:
  mapper-locations: classpath:com/example/qingtingserver/*.xml       # Mapper XML 文件的位置
  configuration:
    map-underscore-to-camel-case: true
server:
  address: 0.0.0.0
  port: 80
